### PR TITLE
Fix include path for clang to grab the proper intree path.

### PR DESCRIPTION
**Pull request by hfiguiere**
I couldn't build on my machine because the clang includes were not found. This looks hackish but if you have the right llvm-config in the right place, it should work. (I override path prior to make)

### CODE REVIEW

**Comment by xiw** [comment]
Looks like you didn't do `make install` for clang...  That's why the clang includes were missing.

**Comment by hfiguiere** [comment]
No I didn't. Neither doc said explicitly to run it, so I assumed it was to be left in place. But when running it I had to trick with path, so...

(I usually don't like to pollute prefix, but I guess I'll install in /opt/llvm and make another PR ;-) )

**Comment by hfiguiere** [comment]
I'll settle for PR #12 then ;-)

**Comment by xiw** [comment]
You are right --- the clang [Getting Started](http://clang.llvm.org/get_started.html) page never mentions `make install`...  Should probably fix our INSTALL instructions.

What I'm doing here is to install clang under my home directory `$(HOME)/usr`, and append `$(HOME)/usr/bin` (where one can find `llvm-config`) to PATH.

**Comment by xiw** [comment]
@hfiguiere Thanks!

**Comment by hfiguiere** [comment]
Hence my other patch to INSTALL ;-)

And yes I thought about doing something similar install-wise. I already had to cheat with the path anyway. Since you say it works that way, it is all good.

**Pull request closed without merging**
