### PR TITLE
get it to compile with clang 3.7

### PR DESCRIPTION
**Pull request by hiraditya**
Hi Xi Wang,
I have updated the stack sources to compile with latest llvm. Please review this and merge if it looks good.
Also, I was trying to run the make check but it failed because of some changes in the plugin API. I wasn't able to figure out the changes required to run make check. It will be great if you could make that change.

Thanks,
-Aditya

### CODE REVIEW

**Comment by xiw** [comment]
@hiraditya thanks!  i'll take a look at it this weekend.

**Comment by hiraditya** [comment]
Thanks.

**Comment by hiraditya** [comment]
Hi Xi Wang,
Did you get a chance to look at the patch? Please let me know if you have any questions.

**Comment by xiw** [comment]
@hiraditya sorry i am traveling and haven't got a chance to test it.  i would definitely want to do that later this week.  another possible change is to use z3 by default since it has a friendly license now.

**Pull request merged**
